In [4]:
l = [21456, 4564564, 45643218]

In [2]:
l

[21456, 4564564, 45643218]

In [6]:
import numpy as np

In [8]:
a = np.array(l)

In [9]:
a

array([   21456,  4564564, 45643218])

In [1]:
b = np.array([12, 455, 63.3, True, ""])

NameError: name 'np' is not defined

In [10]:
a.mean()

16743079.333333334

In [11]:
#---------------------- slicing arrays

In [12]:
a

array([   21456,  4564564, 45643218])

In [13]:
a[2:4]

array([45643218])

In [14]:
b = a[2:4] # a view of variable a

In [15]:
b

array([45643218])

In [16]:
b[:] = 111

In [17]:
b #it changes a too

array([111])

In [18]:
a

array([  21456, 4564564,     111])

In [19]:
c = a.copy() # create a copy of variable a

In [20]:
c

array([  21456, 4564564,     111])

In [21]:
c[0] = 0 # now you can modify  a new array without modifyin variable a

In [22]:
c

array([      0, 4564564,     111])

In [23]:
a

array([  21456, 4564564,     111])